api_key_id = "PKBJM1PXLTXGD2D22A5Q"
api_secret_key = "XWcdlvVpmrzOfwfmkxgvSVDhe9krobxhIa1mzobU"
db_user = "postgres"
db_password = "postgres"
db_server_name = "localhost"
db_database_name = "pythonetl"